name: repro
channels:
- conda-forge
dependencies:
  - jupyter_client
  - dask
  - awscli
  - ipydatagrid
  - ipydatawidgets
  - git
  - boto3
  - pytorch
  - s3fs
  - pip
  - pandera
  - jsonpickle
  - pyjwt
