[project]
name = "repro"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ben Moss <bmoss40@bloomberg.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
jupyter_client = "*"
dask = "*"
awscli = "*"
ipydatagrid = "*"
ipydatawidgets = "*"
git = "*"
boto3 = "*"
pytorch = "*"
s3fs = "*"
pip = "*"
pandera = "*"
jsonpickle = "*"
pyjwt = "*"

[target.osx-arm64.dependencies]
jupyter_client = "*"
dask = "*"
awscli = "*"
ipydatagrid = "*"
ipydatawidgets = "*"
git = "*"
boto3 = "*"
pytorch = "*"
s3fs = "*"
pip = "*"
pandera = "*"
jsonpickle = "*"
pyjwt = "*"

[target.osx-64.dependencies]
jupyter_client = "*"
dask = "*"
awscli = "*"
ipydatagrid = "*"
ipydatawidgets = "*"
git = "*"
boto3 = "*"
pytorch = "*"
s3fs = "*"
pip = "*"
pandera = "*"
jsonpickle = "*"
pyjwt = "*"
