[project]
name = "base"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ben Moss <bmoss40@bloomberg.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]

[target.linux-64.dependencies]
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_kmp_llvm" }
aiobotocore = { version = "==2.12.1", build = "pyhd8ed1ab_0" }
aiohttp = { version = "==3.9.3", build = "py39hd1e30aa_1" }
aioitertools = { version = "==0.11.0", build = "pyhd8ed1ab_0" }
aiosignal = { version = "==1.3.1", build = "pyhd8ed1ab_0" }
astropy = { version = "==5.3.4", build = "py39h44dd56e_2" }
asttokens = { version = "==2.4.1", build = "pyhd8ed1ab_0" }
async-timeout = { version = "==4.0.3", build = "pyhd8ed1ab_0" }
attrs = { version = "==23.2.0", build = "pyh71513ae_0" }
aws-c-auth = { version = "==0.7.8", build = "h538f98c_2" }
aws-c-cal = { version = "==0.6.9", build = "h5d48c4d_2" }
aws-c-common = { version = "==0.9.10", build = "hd590300_0" }
aws-c-compression = { version = "==0.2.17", build = "h7f92143_7" }
aws-c-event-stream = { version = "==0.3.2", build = "h0bcb0bb_8" }
aws-c-http = { version = "==0.7.14", build = "hd268abd_3" }
aws-c-io = { version = "==0.13.36", build = "he0cd244_2" }
aws-c-mqtt = { version = "==0.9.10", build = "h35285c7_2" }
aws-c-s3 = { version = "==0.4.4", build = "h0448019_0" }
aws-c-sdkutils = { version = "==0.1.13", build = "h7f92143_0" }
aws-checksums = { version = "==0.1.17", build = "h7f92143_6" }
aws-crt-cpp = { version = "==0.25.0", build = "h5bdc202_0" }
aws-sdk-cpp = { version = "==1.11.210", build = "h0853bfa_5" }
awscli = { version = "==2.15.30", build = "py39hf3d152e_0" }
awscrt = { version = "==0.19.19", build = "py39hf0530f4_2" }
bokeh = { version = "==3.4.0", build = "pyhd8ed1ab_0" }
boto3 = { version = "==1.34.51", build = "pyhd8ed1ab_0" }
botocore = { version = "==1.34.51", build = "pyge38_1234567_0" }
brotli = { version = "==1.1.0", build = "hd590300_1" }
brotli-bin = { version = "==1.1.0", build = "hd590300_1" }
brotli-python = { version = "==1.1.0", build = "py39h3d6467e_1" }
bzip2 = { version = "==1.0.8", build = "hd590300_5" }
c-ares = { version = "==1.27.0", build = "hd590300_0" }
ca-certificates = { version = "==2024.2.2", build = "hbcca054_0" }
cairo = { version = "==1.18.0", build = "h3faef2a_0" }
certifi = { version = "==2024.2.2", build = "pyhd8ed1ab_0" }
cffi = { version = "==1.16.0", build = "py39h7a31438_0" }
chardet = { version = "==5.2.0", build = "py39hf3d152e_1" }
charset-normalizer = { version = "==3.3.2", build = "pyhd8ed1ab_0" }
ciso8601 = { version = "==2.3.1", build = "py39hd1e30aa_0" }
click = { version = "==8.0.4", build = "py39hf3d152e_0" }
cloudpickle = { version = "==3.0.0", build = "pyhd8ed1ab_0" }
colorama = { version = "==0.4.6", build = "pyhd8ed1ab_0" }
comm = { version = "==0.2.2", build = "pyhd8ed1ab_0" }
contourpy = { version = "==1.2.0", build = "py39h7633fee_0" }
cryptography = { version = "==40.0.2", build = "py39h079d5ae_0" }
cudnn = { version = "==8.9.7.29", build = "hbc23b4c_3" }
curl = { version = "==8.6.0", build = "hca28451_0" }
cycler = { version = "==0.12.1", build = "pyhd8ed1ab_0" }
cytoolz = { version = "==0.12.3", build = "py39hd1e30aa_0" }
dask = { version = "==2023.10.1", build = "pyhd8ed1ab_0" }
dask-core = { version = "==2023.10.1", build = "pyhd8ed1ab_0" }
debugpy = { version = "==1.8.1", build = "py39h3d6467e_0" }
decorator = { version = "==5.1.1", build = "pyhd8ed1ab_0" }
distributed = { version = "==2023.10.1", build = "pyhd8ed1ab_0" }
distro = { version = "==1.8.0", build = "pyhd8ed1ab_0" }
docutils = { version = "==0.19", build = "py39hf3d152e_1" }
exceptiongroup = { version = "==1.2.0", build = "pyhd8ed1ab_2" }
executing = { version = "==2.0.1", build = "pyhd8ed1ab_0" }
expat = { version = "==2.6.2", build = "h59595ed_0" }
filelock = { version = "==3.13.1", build = "pyhd8ed1ab_0" }
font-ttf-dejavu-sans-mono = { version = "==2.37", build = "hab24e00_0" }
font-ttf-inconsolata = { version = "==3.0", build = "h77eed37_0" }
font-ttf-source-code-pro = { version = "==2.38", build = "h77eed37_0" }
font-ttf-ubuntu = { version = "==0.83", build = "h77eed37_1" }
fontconfig = { version = "==2.14.2", build = "h14ed4e7_0" }
fonts-conda-ecosystem = { version = "==1", build = "0" }
fonts-conda-forge = { version = "==1", build = "0" }
fonttools = { version = "==4.49.0", build = "py39hd1e30aa_0" }
freetype = { version = "==2.12.1", build = "h267a509_2" }
frictionless = { version = "==5.14.5", build = "pyhca7485f_0" }
frozenlist = { version = "==1.4.1", build = "py39hd1e30aa_0" }
fsspec = { version = "==2023.12.2", build = "pyhca7485f_0" }
gast = { version = "==0.4.0", build = "pyh9f0ad1d_0" }
gettext = { version = "==0.21.1", build = "h27087fc_0" }
gflags = { version = "==2.2.2", build = "he1b5a44_1004" }
git = { version = "==2.44.0", build = "pl5321h709897a_0" }
git-remote-codecommit = { version = "==1.16", build = "pyhd8ed1ab_0" }
glog = { version = "==0.6.0", build = "h6f12383_0" }
gmp = { version = "==6.3.0", build = "h59595ed_1" }
gmpy2 = { version = "==2.1.2", build = "py39h376b7d2_1" }
groff = { version = "==1.22.4", build = "pl5321h9c3ff4c_1" }
humanize = { version = "==4.9.0", build = "pyhd8ed1ab_0" }
icu = { version = "==73.2", build = "h59595ed_0" }
idna = { version = "==3.6", build = "pyhd8ed1ab_0" }
importlib-metadata = { version = "==7.0.2", build = "pyha770c72_0" }
importlib-resources = { version = "==6.3.0", build = "pyhd8ed1ab_0" }
importlib_metadata = { version = "==7.0.2", build = "hd8ed1ab_0" }
importlib_resources = { version = "==6.3.0", build = "pyhd8ed1ab_0" }
ipydatagrid = { version = "==1.2.1", build = "pyhd8ed1ab_0" }
ipydatawidgets = { version = "==4.3.2", build = "pyhc268e32_0" }
ipython = { version = "==8.17.2", build = "pyh41d4057_0" }
ipywidgets = { version = "==8.1.2", build = "pyhd8ed1ab_0" }
isodate = { version = "==0.6.1", build = "pyhd8ed1ab_0" }
jedi = { version = "==0.19.1", build = "pyhd8ed1ab_0" }
jinja2 = { version = "==3.1.3", build = "pyhd8ed1ab_0" }
jmespath = { version = "==1.0.1", build = "pyhd8ed1ab_0" }
jsonpickle = { version = "==3.0.2", build = "pyhd8ed1ab_1" }
jsonschema = { version = "==4.21.1", build = "pyhd8ed1ab_0" }
jsonschema-specifications = { version = "==2023.12.1", build = "pyhd8ed1ab_0" }
jupyter_client = { version = "==8.6.1", build = "pyhd8ed1ab_0" }
jupyter_core = { version = "==5.7.2", build = "py39hf3d152e_0" }
jupyterlab_widgets = { version = "==3.0.10", build = "pyhd8ed1ab_0" }
keyutils = { version = "==1.6.1", build = "h166bdaf_0" }
kiwisolver = { version = "==1.4.5", build = "py39h7633fee_1" }
krb5 = { version = "==1.21.2", build = "h659d440_0" }
latexcodec = { version = "==2.0.1", build = "pyh9f0ad1d_0" }
lcms2 = { version = "==2.16", build = "hb7c19ff_0" }
ld_impl_linux-64 = { version = "==2.40", build = "h41732ed_0" }
lerc = { version = "==4.0.0", build = "h27087fc_0" }
libabseil = { version = "==20230802.1", build = "cxx17_h59595ed_0" }
libarrow = { version = "==14.0.2", build = "hfb4d3a9_0_cpu" }
libarrow-acero = { version = "==14.0.2", build = "h59595ed_0_cpu" }
libarrow-dataset = { version = "==14.0.2", build = "h59595ed_0_cpu" }
libarrow-flight = { version = "==14.0.2", build = "h120cb0d_0_cpu" }
libarrow-flight-sql = { version = "==14.0.2", build = "h61ff412_0_cpu" }
libarrow-gandiva = { version = "==14.0.2", build = "hacb8726_0_cpu" }
libarrow-substrait = { version = "==14.0.2", build = "h61ff412_0_cpu" }
libblas = { version = "==3.9.0", build = "20_linux64_mkl" }
libbrotlicommon = { version = "==1.1.0", build = "hd590300_1" }
libbrotlidec = { version = "==1.1.0", build = "hd590300_1" }
libbrotlienc = { version = "==1.1.0", build = "hd590300_1" }
libcblas = { version = "==3.9.0", build = "20_linux64_mkl" }
libcrc32c = { version = "==1.1.2", build = "h9c3ff4c_0" }
libcurl = { version = "==8.6.0", build = "hca28451_0" }
libdeflate = { version = "==1.19", build = "hd590300_0" }
libedit = { version = "==3.1.20191231", build = "he28a2e2_2" }
libev = { version = "==4.33", build = "hd590300_2" }
libevent = { version = "==2.1.12", build = "hf998b51_1" }
libexpat = { version = "==2.6.2", build = "h59595ed_0" }
libffi = { version = "==3.4.2", build = "h7f98852_5" }
libgcc-ng = { version = "==13.2.0", build = "h807b86a_5" }
libgfortran-ng = { version = "==13.2.0", build = "h69a702a_5" }
libgfortran5 = { version = "==13.2.0", build = "ha4646dd_5" }
libglib = { version = "==2.80.0", build = "hf2295e7_0" }
libgomp = { version = "==13.2.0", build = "h807b86a_5" }
libgoogle-cloud = { version = "==2.12.0", build = "h5206363_4" }
libgrpc = { version = "==1.59.3", build = "hd6c4280_0" }
libhwloc = { version = "==2.9.3", build = "default_h554bfaf_1009" }
libiconv = { version = "==1.17", build = "hd590300_2" }
libjpeg-turbo = { version = "==3.0.0", build = "hd590300_1" }
liblapack = { version = "==3.9.0", build = "20_linux64_mkl" }
libllvm15 = { version = "==15.0.7", build = "hb3ce162_4" }
libmagma = { version = "==2.7.2", build = "h09b5827_2" }
libmagma_sparse = { version = "==2.7.2", build = "h09b5827_3" }
libnghttp2 = { version = "==1.58.0", build = "h47da74e_1" }
libnl = { version = "==3.9.0", build = "hd590300_0" }
libnsl = { version = "==2.0.1", build = "hd590300_0" }
libparquet = { version = "==14.0.2", build = "h352af49_0_cpu" }
libpng = { version = "==1.6.43", build = "h2797004_0" }
libprotobuf = { version = "==4.24.4", build = "hf27288f_0" }
libre2-11 = { version = "==2023.9.1", build = "h7a70373_1" }
libsodium = { version = "==1.0.18", build = "h36c2ea0_1" }
libsqlite = { version = "==3.45.2", build = "h2797004_0" }
libssh2 = { version = "==1.11.0", build = "h0841786_0" }
libstdcxx-ng = { version = "==13.2.0", build = "h7e041cc_5" }
libthrift = { version = "==0.19.0", build = "hb90f79a_1" }
libtiff = { version = "==4.6.0", build = "ha9c0a0a_2" }
libtorch = "2.1.2.*"
libutf8proc = { version = "==2.8.0", build = "h166bdaf_0" }
libuuid = { version = "==2.38.1", build = "h0b41bf4_0" }
libuv = { version = "==1.48.0", build = "hd590300_0" }
libwebp-base = { version = "==1.3.2", build = "hd590300_0" }
libxcb = { version = "==1.15", build = "h0b41bf4_0" }
libxcrypt = { version = "==4.4.36", build = "hd590300_1" }
libxml2 = { version = "==2.12.6", build = "h232c23b_0" }
libzlib = { version = "==1.2.13", build = "hd590300_5" }
llvm-openmp = { version = "==18.1.1", build = "h4dfa4b3_0" }
locket = { version = "==1.0.0", build = "pyhd8ed1ab_0" }
lz4 = { version = "==4.3.3", build = "py39h79d96da_0" }
lz4-c = { version = "==1.9.4", build = "hcb278e6_0" }
magma = { version = "==2.7.2", build = "h4aca40b_3" }
markdown-it-py = { version = "==3.0.0", build = "pyhd8ed1ab_0" }
marko = { version = "==2.0.3", build = "pyhd8ed1ab_0" }
markupsafe = { version = "==2.1.5", build = "py39hd1e30aa_0" }
matplotlib-base = { version = "==3.8.3", build = "py39he9076e7_0" }
matplotlib-inline = { version = "==0.1.6", build = "pyhd8ed1ab_0" }
mdurl = { version = "==0.1.2", build = "pyhd8ed1ab_0" }
mergedeep = { version = "==1.3.4", build = "pyhd8ed1ab_0" }
micromamba = { version = "==1.3.1", build = "0" }
mkl = { version = "==2023.2.0", build = "h84fe81f_50496" }
mpc = { version = "==1.3.1", build = "hfe3b2da_0" }
mpfr = { version = "==4.2.1", build = "h9458935_0" }
mpmath = { version = "==1.3.0", build = "pyhd8ed1ab_0" }
msgpack-python = { version = "==1.0.7", build = "py39h7633fee_0" }
multidict = { version = "==6.0.5", build = "py39hd1e30aa_0" }
multimethod = { version = "==1.9.1", build = "pyhd8ed1ab_0" }
munkres = { version = "==1.1.4", build = "pyh9f0ad1d_0" }
mypy_extensions = { version = "==1.0.0", build = "pyha770c72_0" }
nccl = { version = "==2.20.5.1", build = "h6103f9b_0" }
ncurses = { version = "==6.4", build = "h59595ed_2" }
nest-asyncio = { version = "==1.6.0", build = "pyhd8ed1ab_0" }
networkx = { version = "==3.2.1", build = "pyhd8ed1ab_0" }
nspr = { version = "==4.35", build = "h27087fc_0" }
nss = { version = "==3.98", build = "h1d7d5a4_0" }
numpy = { version = "==1.26.4", build = "py39h474f0d3_0" }
openjpeg = { version = "==2.5.2", build = "h488ebb8_0" }
openssl = { version = "==3.2.1", build = "hd590300_0" }
orc = { version = "==1.9.2", build = "h4b38347_0" }
packaging = { version = "==24.0", build = "pyhd8ed1ab_0" }
pandas = { version = "==1.5.3", build = "py39h2ad29b5_1" }
pandera = { version = "==0.18.3", build = "hd8ed1ab_0" }
pandera-base = { version = "==0.18.3", build = "pyhd8ed1ab_0" }
parso = { version = "==0.8.3", build = "pyhd8ed1ab_0" }
partd = { version = "==1.4.1", build = "pyhd8ed1ab_0" }
pcre2 = { version = "==10.43", build = "hcad00b1_0" }
pdf2image = { version = "==1.17.0", build = "pyhd8ed1ab_0" }
perl = { version = "==5.32.1", build = "7_hd590300_perl5" }
petl = { version = "==1.7.15", build = "pyhd8ed1ab_0" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_0" }
pickleshare = { version = "==0.7.5", build = "py_1003" }
pillow = { version = "==10.2.0", build = "py39had0adad_0" }
pip = { version = "==24.0", build = "pyhd8ed1ab_0" }
pixman = { version = "==0.43.2", build = "h59595ed_0" }
pkgutil-resolve-name = { version = "==1.3.10", build = "pyhd8ed1ab_1" }
platformdirs = { version = "==4.2.0", build = "pyhd8ed1ab_0" }
poppler = { version = "==24.3.0", build = "h590f24d_0" }
poppler-data = { version = "==0.4.12", build = "hd8ed1ab_0" }
prompt-toolkit = { version = "==3.0.38", build = "pyha770c72_0" }
prompt_toolkit = { version = "==3.0.38", build = "hd8ed1ab_0" }
psutil = { version = "==5.9.8", build = "py39hd1e30aa_0" }
pthread-stubs = { version = "==0.4", build = "h36c2ea0_1001" }
ptyprocess = { version = "==0.7.0", build = "pyhd3deb0d_0" }
pure_eval = { version = "==0.2.2", build = "pyhd8ed1ab_0" }
py2vega = { version = "==0.6.1", build = "pyhd8ed1ab_0" }
pyarrow = { version = "==14.0.2", build = "py39h6925388_0_cpu" }
pyasn1 = { version = "==0.5.1", build = "pyhd8ed1ab_0" }
pybtex = { version = "==0.24.0", build = "pyhd8ed1ab_2" }
pycparser = { version = "==2.21", build = "pyhd8ed1ab_0" }
pydantic = { version = "==1.10.2", build = "py39hb9d737c_1" }
pyerfa = { version = "==2.0.1.1", build = "py39h44dd56e_0" }
pygments = { version = "==2.17.2", build = "pyhd8ed1ab_0" }
pyjwt = { version = "==2.8.0", build = "pyhd8ed1ab_1" }
pyopenssl = { version = "==23.1.1", build = "pyhd8ed1ab_0" }
pyparsing = { version = "==3.1.2", build = "pyhd8ed1ab_0" }
pysocks = { version = "==1.7.1", build = "pyha2e5f31_6" }
python = { version = "==3.9.18", build = "h0755675_1_cpython" }
python-dateutil = { version = "==2.8.2", build = "pyhd8ed1ab_0" }
python-slugify = { version = "==8.0.4", build = "pyhd8ed1ab_0" }
pytorch = "2.1.2.*"
pytz = { version = "==2024.1", build = "pyhd8ed1ab_0" }
pyyaml = { version = "==6.0.1", build = "py39hd1e30aa_1" }
pyzmq = { version = "==24.0.1", build = "py39headdf64_1" }
rdma-core = { version = "==50.0", build = "hd3aeb46_1" }
re2 = { version = "==2023.9.1", build = "h7f4b329_1" }
readline = { version = "==8.2", build = "h8228510_1" }
referencing = { version = "==0.34.0", build = "pyhd8ed1ab_0" }
requests = { version = "==2.31.0", build = "pyhd8ed1ab_0" }
retrying = { version = "==1.3.3", build = "py_2" }
rfc3986 = { version = "==2.0.0", build = "pyhd8ed1ab_0" }
rich = { version = "==13.7.1", build = "pyhd8ed1ab_0" }
rpds-py = { version = "==0.18.0", build = "py39h9fdd4d6_0" }
"ruamel.yaml" = { version = "==0.17.21", build = "py39h72bdee0_3" }
"ruamel.yaml.clib" = { version = "==0.2.7", build = "py39hd1e30aa_2" }
s2n = { version = "==1.4.0", build = "h06160fa_0" }
s3fs = { version = "==2023.12.2", build = "pyhd8ed1ab_0" }
s3transfer = { version = "==0.10.1", build = "pyhd8ed1ab_0" }
scipy = { version = "==1.12.0", build = "py39h474f0d3_2" }
setuptools = { version = "==69.2.0", build = "pyhd8ed1ab_0" }
setuptools-github = { version = "==0.4.2", build = "pyhd8ed1ab_0" }
shellingham = { version = "==1.5.4", build = "pyhd8ed1ab_0" }
simpleeval = { version = "==0.9.13", build = "pyhd8ed1ab_1" }
six = { version = "==1.16.0", build = "pyh6c4a22f_0" }
sleef = { version = "==3.5.1", build = "h9b69904_2" }
snappy = { version = "==1.1.10", build = "h9fff704_0" }
sortedcontainers = { version = "==2.4.0", build = "pyhd8ed1ab_0" }
stack_data = { version = "==0.6.2", build = "pyhd8ed1ab_0" }
stringcase = { version = "==1.2.0", build = "py_0" }
"svg.path" = { version = "==4.1", build = "pyhd8ed1ab_0" }
svgdigitizer = { version = "==0.12.0", build = "pyhd8ed1ab_0" }
svgpathtools = { version = "==1.6.0", build = "pyhd8ed1ab_0" }
svgwrite = { version = "==1.4.3", build = "pyhd8ed1ab_0" }
sympy = { version = "==1.12", build = "pypyh9d50eac_103" }
tabulate = { version = "==0.9.0", build = "pyhd8ed1ab_1" }
tbb = { version = "==2021.11.0", build = "h00ab1b0_1" }
tblib = { version = "==3.0.0", build = "pyhd8ed1ab_0" }
tenacity = { version = "==8.2.3", build = "pyhd8ed1ab_0" }
text-unidecode = { version = "==1.3", build = "pyhd8ed1ab_1" }
tk = { version = "==8.6.13", build = "noxft_h4845f30_101" }
toolz = { version = "==0.12.1", build = "pyhd8ed1ab_0" }
tornado = { version = "==6.4", build = "py39hd1e30aa_0" }
traitlets = { version = "==5.14.2", build = "pyhd8ed1ab_0" }
traittypes = { version = "==0.2.1", build = "pyh9f0ad1d_2" }
typeguard = { version = "==4.1.5", build = "pyhd8ed1ab_1" }
typer = { version = "==0.9.0", build = "pyhd8ed1ab_0" }
typing-extensions = { version = "==4.10.0", build = "hd8ed1ab_0" }
typing_extensions = { version = "==4.10.0", build = "pyha770c72_0" }
typing_inspect = { version = "==0.9.0", build = "pyhd8ed1ab_0" }
tzdata = { version = "==2024a", build = "h0c530f3_0" }
ucx = { version = "==1.15.0", build = "h11edf95_7" }
unicodedata2 = { version = "==15.1.0", build = "py39hd1e30aa_0" }
urllib3 = { version = "==1.26.18", build = "pyhd8ed1ab_0" }
validators = { version = "==0.22.0", build = "pyhd8ed1ab_0" }
wcwidth = { version = "==0.2.13", build = "pyhd8ed1ab_0" }
wheel = { version = "==0.42.0", build = "pyhd8ed1ab_0" }
widgetsnbextension = { version = "==4.0.10", build = "pyhd8ed1ab_0" }
wrapt = { version = "==1.16.0", build = "py39hd1e30aa_0" }
xorg-kbproto = { version = "==1.0.7", build = "h7f98852_1002" }
xorg-libice = { version = "==1.1.1", build = "hd590300_0" }
xorg-libsm = { version = "==1.2.4", build = "h7391055_0" }
xorg-libx11 = { version = "==1.8.7", build = "h8ee46fc_0" }
xorg-libxau = { version = "==1.0.11", build = "hd590300_0" }
xorg-libxdmcp = { version = "==1.1.3", build = "h7f98852_0" }
xorg-libxext = { version = "==1.3.4", build = "h0b41bf4_2" }
xorg-libxrender = { version = "==0.9.11", build = "hd590300_0" }
xorg-renderproto = { version = "==0.11.1", build = "h7f98852_1002" }
xorg-xextproto = { version = "==7.3.0", build = "h0b41bf4_1003" }
xorg-xproto = { version = "==7.0.31", build = "h7f98852_1007" }
xyzservices = { version = "==2023.10.1", build = "pyhd8ed1ab_0" }
xz = { version = "==5.2.6", build = "h166bdaf_0" }
yaml = { version = "==0.2.5", build = "h7f98852_2" }
yarl = { version = "==1.9.4", build = "py39hd1e30aa_0" }
zeromq = { version = "==4.3.5", build = "h59595ed_1" }
zict = { version = "==3.0.0", build = "pyhd8ed1ab_0" }
zipp = { version = "==3.17.0", build = "pyhd8ed1ab_0" }
zlib = { version = "==1.2.13", build = "hd590300_5" }
zstd = { version = "==1.5.5", build = "hfc55251_0" }
